<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--**********************************************-->
    <TieredPGO>true</TieredPGO>
    <DebugType>none</DebugType>
    <!--**********************************************-->
    <ScopedCssEnabled>true</ScopedCssEnabled>
    <EnableDefaultScopedCssItems>true</EnableDefaultScopedCssItems>
    <!--**********************************************-->

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Maanfee.Web.Core" Version="9.20.5" />
    <PackageReference Include="MudBlazor" Version="9.8.0" />
  </ItemGroup>

</Project>
